run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number

linters:
  enable-all: true    # ⚠️ Enables ALL linters, even aggressive ones
  disable:
    - lll              # Line length (annoying for many projects)
    - dupl             # Duplicate code (too noisy without tuning)
    - funlen           # Function length — can be overly strict
    - gochecknoglobals # Often unrealistic for real-world apps
    - godot            # Period at end of comments — style preference
    - gomnd            # Magic numbers — tune manually if desired

linters-settings:
  gofmt:
    simplify: true

  gocyclo:
    min-complexity: 15

  errcheck:
    check-type-assertions: true

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: error-naming
      - name: blank-imports

  unused:
    check-exported: true

  depguard:
    list-type: blacklist
    packages:
      - fmt
    include-go-root: false
    packages-with-error-message:
      fmt: "Use a structured logger instead of fmt"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "is deprecated"
    - "SA1019" # Suppress deprecated field warnings (optional)
