name: personal-secretary-user-api-test

networks:
  shared-network:
    external: true

services:
  mongodb-test:
    container_name: personal-secretary-user-api-mongodb-test
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${APP_MONGO_DATABASE}
    networks:
      - shared-network
    ports:
      - "${APP_MONGO_PORT_APP:-27017}:27017"
    volumes:
      - ./data/_mongodbtest:/data/db
    restart: always